### ISSUE TITLE
Icons in title bar appear wrong

### ISSUE THREAD

**Issue by victorprocure** [lepoco/wpfui#35] opened 2022-01-19 01:08 UTC
**Describe the bug**  
The icons in the title bar look incorrect

**To Reproduce**  
1. Install Windows 11
2. Open app RadioGraph

**Expected behavior**  
Icons look correct

**Screenshots**  
![image](https://user-images.githubusercontent.com/5872342/150044405-1d411c25-f197-4d95-8ef8-7648e2e321ac.png)

**Desktop (please complete the following information):**  
 - OS: Windows 11
 - .NET: Net 6

**Comment by Aelarion** [comment] 2022-01-29 21:27
I actually was able to reproduce this by accident on Windows 10, not sure if it's the same root cause.

Steps:
- Create an empty WPF window
- Set style to `UiWindow`
- In code behind, after `InitializeComponent()`, add `Background.Manager.Apply(BackgroundType.Acrylic, this)`

I'm not quite sure where this is happening since I can't step into the DLL code on my current application. My best guess is somewhere around when the handler that gets assigned to OnLoad, some of that logic is stepping on a style with the window chrome or something. No evidence to support that, just a quick guess.

This is using nuget package WPF-UI 1.2.2-prerelease136.

**Closed** 2022-06-06 22:11 UTC
Labels: bug, themes, controls
