### ISSUE TITLE
Scroll bars do not appear for UiPageScrollable

### ISSUE THREAD

**Issue by BartoszCichecki** [lepoco/wpfui#20] opened 2022-01-01 20:12 UTC
**Describe the bug**  
Scroll bars do not appear when `UiPageScrollable` style is set on `Page`

**To Reproduce**  
1. Open sample app.
2. Scrollable pages do not have scrollbars visible.

**Expected behavior**  
Scroll bars are visible.

**Screenshots**  

**Desktop (please complete the following information):**  
 - OS: Win 11
 - .NET: .net5.0
 - Version: 1.2.2-prerelease111

**Additional context**

**Comment by Aelarion** [comment] 2022-01-24 17:41
I see this one has been tagged as enhancement and not a bug, so just to give some additional context -- in [Styles/Controls/Page.xaml, line 45](https://github.com/lepoco/wpfui/blob/497b89199ce1bc03d7e23ac1a5d42d3b1b61569f/WPFUI/Styles/Controls/Page.xaml#L45) it looks like this is a deliberate design choice.

If you wanted to override the `ControlTemplate` as a stop-gap fix there's a style available in WPFUI (see [UiScrollViewer](https://github.com/lepoco/wpfui/blob/2ff8a5c1af28db949b0bda8c985ce4d2374e0ed9/WPFUI/Styles/Controls/Scroll.xaml#L229)). Would basically just be a copy-paste job of the Page style and in the `ScrollViewer` element assign it `Style="{DynamicResource UiScrollViewer}"`.

For anyone looking to tackle this enhancement, WinUI has some design notes for ScrollViewer controls (see: https://docs.microsoft.com/en-us/windows/apps/design/controls/scroll-controls). Looks like it would be a gigantic pain in the neck to do properly though LOL:

![](https://docs.microsoft.com/en-us/windows/apps/design/controls/images/conscious-scroll.gif)

**Comment by BartoszCichecki** [comment] 2022-01-24 22:44
That does look like a lot of work. It seems to me though, like having something easy to implement and kind of looking like it should (without the fancy animations) would be better than not having scrollbars at all.

**Comment by pomianowski** [comment] 2022-01-24 22:55
It's enough to just make a style:
```xaml
<Style
        x:Key="UiPageScrollable"
        BasedOn="{StaticResource UiPage}"
        TargetType="{x:Type Page}">
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate>
                    <ScrollViewer
                        Margin="0"
                        HorizontalScrollBarVisibility="Disabled"
                        Style="{DynamicResource UiScrollViewer}"
                        VerticalScrollBarVisibility="Visible">
                        <ContentPresenter
                            HorizontalAlignment="Stretch"
                            VerticalAlignment="Stretch"
                            Content="{TemplateBinding ContentControl.Content}" />
                    </ScrollViewer>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>
```

and this way we get a scrollbar
![image](https://user-images.githubusercontent.com/13592821/150878076-1902883a-d8b5-480d-9751-f817f7875b52.png)

But I don't like this approach because the non-disappearing scrollbar doesn't fit the whole thing.
Plus it has to be styled so like @Aelarion said. We have to [copy this scrollbar](https://github.com/lepoco/wpfui/blob/2ff8a5c1af28db949b0bda8c985ce4d2374e0ed9/WPFUI/Styles/Controls/Scroll.xaml#L229) and correct it, then slightly change the approach with margins and it should look somewhat ok.

**Comment by Aelarion** [comment] 2022-01-25 00:38
Just adding some notes for anyone who comes across this issue (this is by no means the actual solution).

If you want a "hidden" scrollbar that only shows when the mouse is over the track, you just have to add some logic to the `PART_Track` opacity in [Styles/Controls/Scroll.xaml](https://github.com/lepoco/wpfui/blob/main/WPFUI/Styles/Controls/Scroll.xaml). Unfortunately this doesn't give you the minimal pill track to fade in while wheel scrolling or touch dragging, but that's not trivial to implement (likely requires extending the control and adding a bit more logic/dependency property/whatever).

By default, set the track `Opacity` to `0` in the `ControlTemplate`:
```
<Track
    x:Name="PART_Track"
    ...
    Opacity="0"
    ...
</Track>
```

In the `ControlTemplate.Triggers`, you want to add a `DoubleAnimation` to the `IsMouseOver` trigger for enter and exit actions (you can just copy the existing `Width` animation). I leave off the "From" value, since you don't want the track to flicker if a mouse is repeatedly going on and off it (without "From" it will just use the current value). For enter, `To="1"` and for exit, `To="0"`. Example:
```
<DoubleAnimation
    Storyboard.TargetName="PART_Track"
    Storyboard.TargetProperty="Opacity"
    To="1"
    Duration="0:0:.16" />
```

Result:

![hiding-scrollbar](https://user-images.githubusercontent.com/38231674/150884640-2e2c8d48-17e3-4a20-b95f-0e82df62c3d2.gif)

**Comment by pomianowski** [comment] 2022-01-25 12:44
@Aelarion, @BartoszCichecki  I linked mouse over to the custom IsScrolling event and could say it works somehow. Just have to tweak the styles.

https://github.com/lepoco/wpfui/blob/33a15169e27c93575be0ec1c34157ef04075681d/WPFUI/Controls/DynamicScrollViewer.cs#L18

![image](https://user-images.githubusercontent.com/13592821/150979017-6e9bf52e-a11e-4725-933c-11e94572bd20.png)

**Closed** 2022-05-03 13:55 UTC
Labels: enhancement, animations, controls
