### ISSUE TITLE
IsPaneVisible not work

### ISSUE THREAD

**Issue by abaa521** [lepoco/wpfui#838] opened 2023-11-23 06:30 UTC
### Describe the bug

I use 3.0.0.0preview4
<ui:NavigationView>
When I set IsPaneVisible to False,Pane always show.

### To Reproduce

set IsPaneVisible to False

### Expected behavior

Pane should not show

### OS version

windows11

### .NET version

.Net6

### WPF-UI NuGet version

3.0.0.0preview4

**Comment by LudwigAspegren** [comment] 2023-11-24 08:15
One way to solve the issue is to add an eventhandler To the the parent Elements load event

`Loaded += RootNavigation.IsPaneOpen = False`

**Comment by tmijail** [comment] 2024-03-21 14:04
Related: #741

**Comment by pomianowski** [comment] 2024-05-28 07:56
Should be fixed in 3.0.4

**Closed by pomianowski** 2024-05-28 07:56 UTC
Labels: bug

**Comment by angeloacedo** [comment] 2025-01-20 15:58
Good day to all. I can still reproduce the issue in version 3.0.5 of the library. Setting IsPaneVisible to TRUE or FALSE has no effect. A possible workaround is setting OpenPaneLength="0" to hide the pane.

**Comment by angeloacedo** [comment] 2025-01-21 05:45
> `IsPaneVisible` got no code references besied it's definition. So I guess that's why it's not working
> 
> https://github.com/search?q=repo%3Alepoco%2Fwpfui%20IsPaneVisible&type=code

Exactly. The permanent solution to this issue would involve modifying the three XAML files—NavigationViewCompact.xaml, NavigationViewTop.xaml, and NavigationViewBottom.xaml—and adding a template binding of the IsPaneVisible property to the Visibility property of the 'PaneGrid' in those files.
